### ISSUE TITLE
[ERR] Command must be run from a package folder

### ISSUE THREAD

**Issue by jbrechbuehl** [vadimpopa/sencha-font-awesome-5#1]
Hi,

Im trying to use your package but Im stuck with step 2.
When I run the command "sencha package build" I got the error: "[ERR] Command must be run from a package folder"

What I did:
1) I downloaded your repository as ZIP
2) I unzipped into the folder "C:\Users\John\workspace_dev\project\src\main\webapp\packages\local\font-awesome-5"
3) I run "sencha package build" from "C:\Users\John\workspace_dev\project\src\main\webapp\packages\local\font-awesome-5" and have the error "[ERR] Command must be run from a package folder"

> John@WINDOWS MINGW64 ~/workspace_dev/project/src/main/webapp/packages/local/font-awesome-5 (john)
> $ sencha package build
> Sencha Cmd v6.2.1.29
> [ERR] Command must be run from a package folder
> 
> John@WINDOWS MINGW64 ~/workspace_dev/project/src/main/webapp/packages/local/font-awesome-5 (john)
> $ ls -al
> total 43
> drwxr-xr-x 1 John 197121     0 Apr 20 20:34 ./
> drwxr-xr-x 1 John 197121     0 Apr 20 20:25 ../
> -rw-r--r-- 1 John 197121     5 Apr 20 20:25 .gitignore
> -rw-r--r-- 1 John 197121   632 Apr 20 20:25 Readme.md
> -rw-r--r-- 1 John 197121  3850 Apr 20 20:25 build.xml
> drwxr-xr-x 1 John 197121     0 Apr 20 20:25 examples/
> -rw-r--r-- 1 John 197121   114 Apr 20 20:25 index.js
> drwxr-xr-x 1 John 197121     0 Apr 20 20:25 licenses/
> drwxr-xr-x 1 John 197121     0 Apr 20 20:25 overrides/
> -rw-r--r-- 1 John 197121  5316 Apr 20 20:25 package.json
> drwxr-xr-x 1 John 197121     0 Apr 20 20:25 resources/
> drwxr-xr-x 1 John 197121     0 Apr 20 20:25 sass/
> -rw-r--r-- 1 John 197121 23009 Apr 20 20:34 sencha-error-20190420.log
> drwxr-xr-x 1 John 197121     0 Apr 20 20:25 src/

Im using ExtJS 6.2.0.981 and Sencha Cmd 6.2.1.29. 

The error log file:

> Sencha Cmd 6.2.1.29 - Crash report
> An error occurred while executing the following command: build package
> 
> Diagnostic information:
>                          app.archivePath : archive/${build.id}                               
>                       app.bootstrap.base : C:\Users\john\workspace_dev\project\src\main\webapp
>                        app.bootstrap.css : bootstrap.css                                     
>                app.bootstrap.microloader : bootstrap.js                                      
> app.builds.preprod.buildOptions.enableSelenium : true                                              
>          app.builds.preprod.cache.enable : true                                              
>       app.builds.preprod.compressor.type : yui                                               
>  app.builds.preprod.js.0.includeInBundle : true                                              
>             app.builds.preprod.js.0.path : ux/selenium.js                                    
>             app.builds.preprod.js.length : 1                                                 
>          app.builds.preprod.loader.cache : ${build.timestamp}                                
> app.builds.preprod.output.appCache.enable : true                                              
>  app.builds.preprod.output.appCache.path : cache.appcache                                    
>           app.builds.preprod.output.base : C:\Users\john\workspace_dev\project\src\main\webapp/build/preprod/MyProject
>              app.builds.preprod.temp.dir : C:\Users\john\workspace_dev\project\src\main\webapp/build/temp/preprod/MyProject
>                         app.cache.deltas : true                                              
>                         app.cache.enable : false                                             
>                            app.classpath : app,ux                                            
>                          app.classpath.0 : app                                               
>                          app.classpath.1 : ux                                                
>                     app.classpath.length : 2                                                 
>                          app.cmd.version : 6.2.1.29                                          
>                           app.config.dir : C:\Users\john\workspace_dev\project\src\main\webapp\.sencha\app
>                 app.cordova.cache.enable : false                                             
>                    app.cordova.config.id : com.domain.MyProject                          
>                  app.cordova.config.name : MyProject                                     
>                  app.cordova.config.path : C:\Users\john\workspace_dev\project\src\main\webapp/cordova
>                app.cordova.config.target :                                                   
>               app.cordova.config.verbose : false                                             
>                    app.cordova.js.0.path : cordova.js                                        
>                app.cordova.js.0.priority : 1000                                              
>                  app.cordova.js.0.remote : true                                              
>                    app.cordova.js.length : 1                                                 
>                  app.cordova.microloader : C:\Users\john\workspace_dev\project\src\main\webapp\.sencha\app/Microloader.js
>       app.cordova.output.appCache.enable : false                                             
>                  app.cordova.output.base : C:\Users\john\workspace_dev\project\src\main\webapp/cordova/www
>              app.cordova.output.manifest : ${build.id}.json                                  
>                  app.cordova.output.page : index.html                                        
> app.development.buildOptions.enableSelenium : true                                              
>     app.development.js.0.includeInBundle : false                                             
>                app.development.js.0.path : ux/selenium.js                                    
>                app.development.js.length : 1                                                 
>              app.development.watch.delay : 250                                               
>                                  app.dir : C:\Users\john\workspace_dev\project\src\main\webapp
>               app.fashion.inliner.enable : false                                             
>                            app.framework : ext                                               
>                    app.framework.version : 6.2.0.981                                         
>                                   app.id : 46545619-914f-4b01-a900-e4ac691f4fdd              
>                        app.indexHtmlPath : index.jsp                                         
>                         app.loader.cache : false                                             
>                    app.loader.cacheParam : _dc                                               
>                                 app.name : MyProject                                     
>               app.output.appCache.enable : false                                             
>                          app.output.base : C:\Users\john\workspace_dev\project\src\main\webapp/build/${build.environment}/MyProject
>            app.output.microloader.enable : true                                              
>                     app.output.page.path : index.jsp                                         
>                            app.overrides : C:\Users\john\workspace_dev\project\src\main\webapp/overrides,C:\Users\john\workspace_dev\project\src\main\webapp/locale/${app.locale}
>                app.phonegap.cache.enable : false                                             
>                   app.phonegap.config.id : com.domain.MyProject                          
>                 app.phonegap.config.name : MyProject                                     
>                 app.phonegap.config.path : C:\Users\john\workspace_dev\project\src\main\webapp/phonegap
>               app.phonegap.config.remote : false                                             
>              app.phonegap.config.verbose : false                                             
>                   app.phonegap.js.0.path : cordova.js                                        
>               app.phonegap.js.0.priority : 1000                                              
>                 app.phonegap.js.0.remote : true                                              
>                   app.phonegap.js.length : 1                                                 
>                 app.phonegap.microloader : C:\Users\john\workspace_dev\project\src\main\webapp\.sencha\app/Microloader.js
>      app.phonegap.output.appCache.enable : false                                             
>                 app.phonegap.output.base : C:\Users\john\workspace_dev\project\src\main\webapp/phonegap/www
>             app.phonegap.output.manifest : ${build.id}.json                                  
>                 app.phonegap.output.page : index.html                                        
> app.production.buildOptions.enableSelenium : false                                             
>              app.production.cache.enable : true                                              
>           app.production.compressor.type : yui                                               
>              app.production.loader.cache : ${build.timestamp}                                
>    app.production.output.appCache.enable : true                                              
>      app.production.output.appCache.path : cache.appcache                                    
>                       app.resource.paths :                                                   
>                         app.sass.dynamic : true                                              
>                             app.sass.etc : sass/etc/all.scss                                 
>                           app.sass.etc.0 : sass/etc/all.scss                                 
>                      app.sass.etc.length : 1                                                 
>                   app.sass.generated.src : sass/save                                         
>                   app.sass.generated.var : sass/save.scss                                    
>                       app.sass.namespace : MyProject                                     
>                             app.sass.src : sass/src                                          
>                           app.sass.src.0 : sass/src                                          
>                      app.sass.src.length : 1                                                 
>                             app.sass.var : sass/var/all.scss,sass/var                        
>                           app.sass.var.0 : sass/var/all.scss                                 
>                           app.sass.var.1 : sass/var                                          
>                      app.sass.var.length : 2                                                 
>                  app.slicer.cache.enable : false                                             
>         app.slicer.js.0.isWidgetManifest : true                                              
>                     app.slicer.js.0.path : C:\Users\john\workspace_dev\project\src\main\webapp/sass/example/custom.js
>                     app.slicer.js.length : 1                                                 
>        app.slicer.output.appCache.enable : false                                             
>  app.testing.buildOptions.enableSelenium : true                                              
>         app.testing.js.0.includeInBundle : true                                              
>                    app.testing.js.0.path : ux/selenium.js                                    
>                    app.testing.js.length : 1                                                 
>                                app.theme : theme-triton                                      
>                              app.toolkit : classic                                           
>                              app.version : 1.0.0.0                                           
>            build.options..enableSelenium : true                                              
>                     buildenvironment.dir : C:\Users\john\workspace_dev\project\src\main\webapp
>                buildenvironment.load.dir : C:\Users\john\workspace_dev\project\src\main\webapp\packages\local\font-awesome-5
>                           cmd.config.dir : C:\SenchaCmd\6.2.1.29                             
>                                  cmd.dir : C:\SenchaCmd\6.2.1.29                             
>                     cmd.framework.minver : 5.5.0                                             
>                    cmd.framework.version : 99.99                                             
>                             cmd.jvm.args : -Xms128m -Xmx1024m -Dapple.awt.UIElement=true     
>               cmd.merge.tool.args.araxis : -wait -merge -3 -a1 {base} {user} {generated} {out}
>               cmd.merge.tool.args.kdiff3 : {base} {user} {generated} -o {out}                
>              cmd.merge.tool.args.p4merge : {base} {user} {generated} {out}                   
>            cmd.merge.tool.args.smartsync : {user} {generated} {base}                         
>           cmd.merge.tool.args.sourcegear : --merge --result={out} {user} {base} {generated}  
>             cmd.merge.tool.args.tortoise : -base:{base} -theirs:{generated} -mine:{user} -merged:{out}
>                               cmd.minver : 3.0.0.0                                           
>                             cmd.platform : windows                                           
>                      cmd.unicode.escapes : C:\SenchaCmd\6.2.1.29/unicode-escapes.json        
>                              cmd.version : 6.2.1.29                                          
>                             cmd.web.port : 1841                                              
>                      config.skipDownload : true                                              
>                       config.skipInherit : false                                             
>                         ext.license.name : gpl                                               
>                      framework.build.dir : ${package.output.base}                            
>                      framework.classpath : ${package.dir}/src                                
>                     framework.cmd.minver : 6.2.0.103                                         
>                    framework.cmd.version : 6.2.0.103                                         
>                  framework.compatVersion : 6.2.0                                             
>                     framework.config.dir : C:\SenchaCmd\6.2.1.29\plugins\ext\current         
>                        framework.creator : Sencha                                            
>            framework.detailedDescription : Sencha Ext JS JavaScript Framework                
>                            framework.dir : C:\Users\john\workspace_dev\project\src\main\webapp\ext
>                   framework.example.apps : admin-dashboard,executive-dashboard,feed-viewer,kitchensink,calendar,classic/desktop,classic/ticket-app,classic/portal,classic/simple-tasks,classic/responsive-app,classic/aria,modern/addressbook,modern/blackberry,modern/energy,modern/stockapp,modern/states,modern/geocongress,modern/oreilly
>                 framework.example.apps.0 : admin-dashboard                                   
>                 framework.example.apps.1 : executive-dashboard                               
>                framework.example.apps.10 : classic/aria                                      
>                framework.example.apps.11 : modern/addressbook                                
>                framework.example.apps.12 : modern/blackberry                                 
>                framework.example.apps.13 : modern/energy                                     
>                framework.example.apps.14 : modern/stockapp                                   
>                framework.example.apps.15 : modern/states                                     
>                framework.example.apps.16 : modern/geocongress                                
>                framework.example.apps.17 : modern/oreilly                                    
>                 framework.example.apps.2 : feed-viewer                                       
>                 framework.example.apps.3 : kitchensink                                       
>                 framework.example.apps.4 : calendar                                          
>                 framework.example.apps.5 : classic/desktop                                   
>                 framework.example.apps.6 : classic/ticket-app                                
>                 framework.example.apps.7 : classic/portal                                    
>                 framework.example.apps.8 : classic/simple-tasks                              
>                 framework.example.apps.9 : classic/responsive-app                            
>            framework.example.apps.length : 18                                                
>                   framework.example.path : examples,templates                                
>                 framework.example.path.0 : examples                                          
>                 framework.example.path.1 : templates                                         
>            framework.example.path.length : 2                                                 
>                         framework.format : 1                                                 
>                           framework.isV5 : true                                              
>                           framework.isV6 : true                                              
>                           framework.name : ext                                               
>                      framework.namespace : Ext                                               
>                         framework.output : ${package.dir}/build                              
>                      framework.overrides : ${package.dir}/overrides                          
>                   framework.packages.dir : C:\Users\john\workspace_dev\project\src\main\webapp\ext/packages/,C:\Users\john\workspace_dev\project\src\main\webapp\ext/classic
>                 framework.resource.paths : resources                                         
>               framework.resource.paths.0 : resources                                         
>          framework.resource.paths.length : 1                                                 
>                       framework.sass.etc : ${package.dir}/sass/etc/all.scss                  
>                   framework.sass.fashion : true                                              
>                 framework.sass.namespace : Ext                                               
>                       framework.sass.src : ${package.dir}/sass/src                           
>                       framework.sass.var : ${package.dir}/sass/var                           
>                        framework.subpkgs : classic/classic,modern/modern,packages/charts,packages/amf,packages/soap,packages/ux,packages/google,packages/legacy,packages/font-awesome,packages/font-pictos,packages/font-ext
>                      framework.subpkgs.0 : classic/classic                                   
>                      framework.subpkgs.1 : modern/modern                                     
>                     framework.subpkgs.10 : packages/font-ext                                 
>                      framework.subpkgs.2 : packages/charts                                   
>                      framework.subpkgs.3 : packages/amf                                      
>                      framework.subpkgs.4 : packages/soap                                     
>                      framework.subpkgs.5 : packages/ux                                       
>                      framework.subpkgs.6 : packages/google                                   
>                      framework.subpkgs.7 : packages/legacy                                   
>                      framework.subpkgs.8 : packages/font-awesome                             
>                      framework.subpkgs.9 : packages/font-pictos                              
>                 framework.subpkgs.length : 11                                                
>                        framework.summary : Ext JS                                            
>                           framework.type : framework                                         
>                        framework.version : 6.2.0.981                                         
>                        inspector.address : http://localhost:1839/                            
>                     package.sass.dynamic : true                                              
>                           repo.local.dir : C:\SenchaCmd\repo                                 
>                               skip.slice : 1                                                 
>                           skip.web.start : true                                              
>         system.java.net.useSystemProxies : true                                              
>                               theme.name : theme-triton                                      
>                             toolkit.name : classic                                           
>                      workspace.build.dir : C:\Users\john\workspace_dev\project\src\main\webapp/build
>                    workspace.cmd.version : 6.2.1.29                                          
>                     workspace.config.dir : C:\Users\john\workspace_dev\project\src\main\webapp\.sencha\workspace
>                            workspace.dir : C:\Users\john\workspace_dev\project\src\main\webapp
>            workspace.frameworks.ext.path : C:\Users\john\workspace_dev\project\src\main\webapp\ext
>         workspace.frameworks.ext.version : 6.2.0.981                                         
>                   workspace.packages.dir : C:\Users\john\workspace_dev\project\src\main\webapp/packages/local,C:\Users\john\workspace_dev\project\src\main\webapp/packages
>               workspace.packages.extract : C:\Users\john\workspace_dev\project\src\main\webapp/packages/remote
>                      workspace.theme.dir : C:\Users\john\workspace_dev\project\src\main\webapp/packages/local,C:\Users\john\workspace_dev\project\src\main\webapp/packages/${args.themeName}
> 
> Exception information:
> java.lang.NullPointerException
>      at java.io.File.<init>(Unknown Source)
>      at com.sencha.util.FileUtil.readFile(FileUtil.java:158)
>      at com.sencha.tools.compiler.jsb.projects.JsbBuilder.processBuild(JsbBuilder.java:29)
>      at com.sencha.command.build.JsbCommand.execute(JsbCommand.java:15)
>      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>      at java.lang.reflect.Method.invoke(Unknown Source)
>      at com.sencha.util.MethodInvoker$Arguments.invoke(MethodInvoker.java:175)
>      at com.sencha.cli.Command.dispatch(Command.java:43)
>      at com.sencha.cli.Commands.dispatch(Commands.java:64)
>      at com.sencha.command.Sencha.dispatch(Sencha.java:79)
>      at com.sencha.command.Sencha.main(Sencha.java:147)
>      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>      at java.lang.reflect.Method.invoke(Unknown Source)
>      at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
>      at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:101)
>      at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:26)

Do you have an idea what's wrong? 

Thanks a lot for sharing your work. I always wanted to upgrade to font awesome 5 but I never had the courage to do it.

**Comment by jbrechbuehl** [comment]
Maybe I need the ".sencha" folder ?

**Comment by vadimpopa** [comment]
No don't think. With latest Sencha Cmd v6.7.0.63, works. Can you try with a newer CMD ?

**Comment by jbrechbuehl** [comment]
Thank you it works with the latest Sencha cmd version. I had to name the folder "project/ext/packages/**font-awesome-5**" instead of "project/ext/packages/**font-awesome**".

Now I'm stuck with step 3: where should I add these variables? Im using the default theme "theme-triton".

**Comment by vadimpopa** [comment]
If you need only FA5 in the app, you don't need to rename the folder. Today I pushed new changes you and should download the repo again, and start from 1. Now FA5 replaces FA4 from ext/packages completley as there's no other way to get rid of FA4, even if they work well both together, having FA4 will make css bundles biggern than needed.

**Comment by vadimpopa** [comment]
Also, will update the readme in a bit with where to add those vars

**Comment by vadimpopa** [comment]
Ok, so now step 3 is done automatically within packages/local/font-awesome/sass/var/all.scss.

**Comment by vadimpopa** [comment]
Seeing no more feedback from you, probably you don't have any issues so closing.

**Comment by jbrechbuehl** [comment]
Hi, 
sorry for the delay, I was very busy these past days. I just tried now the new version and it works like charm. Thanks a lot. Great work.
